#!/bin/bash

mkdir -p cropped

counter=1;
zero="0"
for i in ./originals/*; do
	if [ $counter -eq 10 ]; then
		zero="";
	fi
	convert $i -gravity Center -crop 100%x80%+0+0 ./cropped/$zero$counter.jpg;
	counter=$((counter + 1));
done;
