#!/bin/bash

append='
# LOCALE (to avoid them being set to brazillian)
LC_ADDRESS="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"

# MISCELLANEOUS
LS_COLORS="*.md=1;36:"$LS_COLORS
LS_COLORS="*.txt=1;36:"$LS_COLORS
LS_COLORS="*.pdf=1;31:"$LS_COLORS
HISTSIZE=1000
HISTFILESIZE=2000

# ALIASES
alias mark=remarkable
alias le=elf-ls
alias rm="rm -I"

# Check backup
l-backupcheck;
'

if [ -a ~/.bashrc ]; then
	echo "Appending the following commands to ~/.bashrc";
	echo;
	echo "==================";
	echo -n "$append";
	echo "==================";
	echo "$append" >> ~/.bashrc;
else
	echo "~/.bashrc does not exist.";
fi
