#!/bin/bash

function alert {
	echo;
	echo "=====";
	echo "========== $@";
	echo "=====";
	echo;
}

function query {
	answer=""
	while [[ "$answer" != "Y" && "$answer" != "y" ]]; do
		echo -n "Next? [Y/n] ";
		read -n 1 answer;
		echo;
	done
	echo;
}

alert BASHRC
echo "Append './appends/bashrc-app' to '~/.bashrc'";
query;

alert PROFILE
echo "Append './appends/profile-app' to '~/.profile'";
query;

alert GIT IGNORE
echo "Append './appends/gitignore_global-app' to '~/.gitignore_global'";
query;

alert VIMRC
echo "Append './appends/vimrc-app' to '~/.vimrc'";
query;

alert VIM SYNTAX
echo "Append './appends/cuda.vim-app' to '~/.vim/after/syntax/cuda.vim'";
query;

alert VIM DICTS
echo "Add vim dictionaries to '~/.vim/dicts/'";
query;

alert GNUPG
echo "Copy .gnupg folder from another of your machines.";
echo "You can also import keys, but it will mess up ownership.";
query;

alert SSH
echo "Copy .ssh folder from another of your machines.";
echo "You can also just copy the remote id_rsa and id_rsa.pub to the local .ssh folder. To make";
echo "  the local machine accessible, copy the id_rsa.pub to the authorized_keys file.";
query;

alert PASS
echo "Copy .password-store folder from another of your machines (must be after copying the gnupg folders).";
echo "You can also pull it directly from the git repository.";
query;
