#!/bin/bash

function alert {
	echo;
	echo "=====";
	echo "========== $@";
	echo "=====";
	echo;
}

function query {
	answer=""
	while [[ "$answer" != "Y" && "$answer" != "y" ]]; do
		echo -n "Next? [Y/n] ";
		read -n 1 answer;
		echo;
	done
	echo;
}

alert APPENDS
echo "See './appends/' and perform the due appends.";
query;

alert FULL-VERSIONS
echo "See './full-versions/' and see which full version files you want to use.";
echo "Careful to not unintentionally erase existing files.";
query;

alert VIM SYNTAX
echo "Move the syntax files in './full-versions/' to '~/.vim/after/syntax/'";
query;

alert VIM DICTS
echo "Add vim dictionaries to '~/.vim/dicts/'";
query;

alert GNUPG
echo "Copy .gnupg folder from another of your machines.";
echo "You can also import keys, but it will mess up ownership.";
query;

alert SSH
echo "Copy .ssh folder from another of your machines.";
echo "You can also just copy the remote id_rsa and id_rsa.pub to the local .ssh folder. To make";
echo "  the local machine accessible, copy the id_rsa.pub to the authorized_keys file.";
query;

alert PASS
echo "Copy .password-store folder from another of your machines (must be after copying the gnupg folders).";
echo "You can also pull it directly from the git repository.";
query;

alert CONFIGURATIONS
echo "Check the folders .local/ .conf/ and .cache/ in your main backup storage."
echo "Copy to the respective folders in the new machine ONLY the folders you think will matter"
query;

alert FIREFOX
echo "Double check if you copied mozilla folders in .local/ .conf/ and .cache/"
echo "Copy ~/.mozilla to the new machine too!!!!"
query;
