#!/bin/bash

append='
PATH="$HOME/bin:$PATH"
'

if [ -a ~/.profile ]; then
	echo "Appending the following content to ~/.profile";
	echo "===============";
	echo -n "$append";
	echo "===============";
	echo "$append" >> ~/.profile;
else
	echo "~/.profile does not exist.";
fi;
