#!/bin/bash

append="
set clipboard=unnamed
set autoindent
set ruler
colo default
set shiftwidth=4
set tabstop=4
set list lcs=tab:^\ ,trail:@

\" set cuda filetype detection
au BufNewFile,BufRead *.cu set ft=cuda
au BufNewFile,BufRead *.cuh set ft=cuda

\" For all text files set 'textwidth' to 150 characters.
autocmd FileType text setlocal textwidth=150

\" Add python dictionary
if has(\"autocmd\")
	autocmd FileType python set complete+=k/home/mathjs/.vim/dicts/python-dict isk+=.,(
endif
"

if ! [ -a ~/.vimrc ]; then
	echo "Creating ~/.vimrc";
	cp ./full-versions/.vimrc ~/.vimrc;
else
	echo "~/.vimrc already exists. Consider appending the following lines to it:";
	echo;
	echo "$append";
fi;


append="
syn keyword cudaFunction	cudaMalloc cudaFree
syn keyword cudaFunction	cudaMemcpy cudaMemcpyAsync
syn keyword cudaFunction	cudaMemset cudaMemsetAsync
syn keyword cudaFunction	cudaStreamCreate cudaStreamDestroy
syn keyword cudaFunction	cudaDeviceSynchronize
syn keyword cudaFunction	__syncthreads

syn keyword cudaType		cudaStream_t

hi def link cudaFunction	Function
"

if ! [ -a ~/.vim/after/syntax/cuda.vim ]; then
	echo "Creating ~/.vim/after/syntax/cuda.vim";
	mkdir -p ~/.vim/after/syntax;
	echo "$append" > ~/.vim/after/syntax/cuda.vim;
else
	echo "~/.vim/after/syntax/cuda.vim already exists";
fi;


echo "We added to .vimrc lines of code for reading some language dictionaries."
echo "Make sure to download these dictionaries, OK?"

while [[ "$answer" != "Y" && "$answer" != "y" ]]; do
	echo "Understood? [Y/n]";
	read -n 1 answer;
done
