#!/bin/bash
echo "Copy .gnupg folder from another of your machines.";
echo "You can also import keys, but it will mess up ownership.";

echo;

while [[ "$answer" != "Y" && "$answer" != "y" ]]; do
	echo "Understood? [Y/n]";
	read -n 1 answer;
done
