#!/bin/bash
echo "Copy .password-store folder from another of your machines.";
echo "You can also pull it directly from the git repository.";

echo;

while [[ "$answer" != "Y" && "$answer" != "y" ]]; do
	echo "Understood? [Y/n]";
	read -n 1 answer;
done
